version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_doc_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./generated_docs:/app/generated_docs
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
